title: Yoshifumi Hanada
description: PhD researcher working on natural language processing for the Ainu language.
url: "https://nonotoy.github.io"
baseurl: ""

markdown: kramdown
timezone: Asia/Tokyo

sass:
  style: compressed
  sass_dir: _sass

exclude:
  - README.md
  - LICENSE.md
  - wip.md
  - history.md
  - vendor
